---
# handlers file for dns-adblock

- name: restart dnsmasq
  service: name=dnsmasq state=restarted

- name: restart apparmor
  service: name=apparmor state=restarted

- name: restart strongswan
  service: name=strongswan state=restarted